databases:
  - name: lunch_pick_app
    databaseName: lunch_pick_app
    user: lunch_pick_app
    plan: free

services:
  - type: web
    plan: free
    name: lunch_pick_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lunch_pick_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
