development:
  adapter: postgresql
  encoding: utf8
  database: lunch_app_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: lunch_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: lunch_app_production
  pool: 5
  username: lunch_app
  password: <%= ENV['DB_PASSWORD'] %>
